# Generated by Django 5.2.2 on 2025-06-20 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiketbus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=8)),
                ('jumlah_bangku', models.PositiveSmallIntegerField()),
                ('jurusan', models.CharField(max_length=30)),
                ('waktu_berangkat', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_telpon', models.CharField(blank=True, max_length=12, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeTiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_bangku', models.IntegerField()),
                ('type_tiket', models.CharField(max_length=8)),
                ('kode_tiket', models.CharField(max_length=12, unique=True)),
                ('status', models.BooleanField()),
                ('tiketbus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiket', to='base.tiketbus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_tikets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PesananTiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.CharField(max_length=10)),
                ('waktu', models.TimeField(blank=True, null=True)),
                ('kode_pesanan', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesanan_tikets', to=settings.AUTH_USER_MODEL)),
                ('tiketbus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tiketbus')),
                ('kode_tiket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesanan', to='base.typetiket', to_field='kode_tiket')),
            ],
        ),
    ]
